steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Test
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['run', 'test:unit']

  # Build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Apply Target for Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['target:apply', 'hosting', 'thunderbandit', 'thunderbandit']

  # Deploy
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--only', 'hosting:thunderbandit']