stages:
  - Build
  # - Test
  - Deploy

build:
  stage: Build
  image: registry.gitlab.com/parvursus/thunderbandit
  only:
    - master
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - build/*
      - node_modules/*
      - public/*
      - src/*
      - .firebaserc
      - firebase.json
      - package.json
      - package-lock.json

deploy:
  stage: Deploy
  image: registry.gitlab.com/parvursus/thunderbandit
  only:
    - master
  # get artifact
  script:
    - npm install firebase-tools
    - ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
  dependencies:
    - build
  when: manual
