defaults: &defaults
  working_directory: /tmp/workspace
  docker:
    - image: circleci/node:8.11.2-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm test

      - run:
          name: Build React App
          command: npm run build

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - build/*
            - node_modules/*
            - public/*
            - src/*
            - .firebaserc
            - firebase.json
            - package.json
            - package-lock.json

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Install Firebase Tools
          command: npm install firebase-tools

      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
